ARG R_VERSION=4.2.0
ARG CIRCLE_PULL_REQUEST

FROM deepnote/ir:${R_VERSION}${CIRCLE_PULL_REQUEST:+-ra-${CIRCLE_PULL_REQUEST##*/}}

# Install the R libraries
RUN R -e "install.packages('tidyverse', repos='https://cloud.r-project.org', dependencies=TRUE)"
RUN R -e "install.packages('data.table', repos='https://cloud.r-project.org', dependencies=TRUE)"
RUN R -e "install.packages('RSQLite', repos='https://cloud.r-project.org', dependencies=TRUE)"
RUN R -e "install.packages('remotes', repos='https://cloud.r-project.org', dependencies=TRUE)"
RUN R -e "install.packages('reticulate', repos='https://cloud.r-project.org', dependencies=TRUE)"
RUN R -e "install.packages('igraph', repos='https://cloud.r-project.org', dependencies=TRUE)"
RUN R -e "install.packages('plotly', repos='https://cloud.r-project.org', dependencies=TRUE)"


# Workaround for Java to install correctly
RUN mkdir -p /usr/share/man/man1/

RUN R -e "install.packages('rgl', repos='https://cloud.r-project.org', dependencies=TRUE)"
RUN R -e "install.packages('hdf5r', repos='https://cloud.r-project.org', dependencies=TRUE)"
RUN R -e "install.packages('rJava', repos='https://cloud.r-project.org', dependencies=TRUE)"