ARG R_VERSION=4.2.0
ARG CIRCLE_PULL_REQUEST

FROM deepnote/ir:${R_VERSION}${CIRCLE_PULL_REQUEST:+-ra-${CIRCLE_PULL_REQUEST##*/}}

# Workaround for Java to install correctly
RUN mkdir -p /usr/share/man/man1/

# Install R lib dependencies
ENV BUILDDEPS="\
default-jdk \
devscripts \
libbz2-dev \
libcairo2-dev \
libcurl4-openssl-dev \
libgit2-dev \
libicu-dev \
libjpeg-dev \
liblzma-dev \
libmagick++-dev \
libpango1.0-dev \
libpcre2-dev \
libpng-dev \
libreadline-dev \
librsvg2-dev \
libtiff5-dev \
libudunits2-dev \
libv8-dev \
libx11-dev \
libxml2-dev \
libxt-dev \
perl \
rsync \
subversion \
tcl-dev \
texinfo \
texlive-extra-utils \
texlive-fonts-extra \
texlive-fonts-recommended \
texlive-latex-extra \
texlive-latex-recommended \
tk-dev \
wget \
x11proto-core-dev \
xauth \
xfonts-base \
xvfb \
zlib1g-dev"

# Use Posit Package Manager for precompiled Linux binaries
ENV CRAN_REPO="https://packagemanager.posit.co/cran/__linux__/bullseye/latest"

# R packages to install
ENV R_PACKAGES="\
tidyverse \
data.table \
RSQLite \
remotes \
reticulate \
igraph \
plotly \
rgl \
hdf5r \
rJava"

RUN apt-get update \
  && apt-get install -y ${BUILDDEPS} \
  && R -e " \
    options(Ncpus = 4); \
    install.packages( \
      strsplit(Sys.getenv('R_PACKAGES'), '\\\\s+')[[1]], \
      repos = Sys.getenv('CRAN_REPO'), \
      dependencies = TRUE \
    ) \
  " \
  && apt-get clean \
  && apt-get remove --purge -y ${BUILDDEPS} \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
