ARG R_VERSION=4.2.0
ARG CIRCLE_PULL_REQUEST

FROM deepnote/ir:${R_VERSION}${CIRCLE_PULL_REQUEST:+-ra-${CIRCLE_PULL_REQUEST##*/}}

# Install the R libraries
RUN R -e "install.packages(c('tidyverse', 'data.table', 'RSQLite', 'remotes', 'reticulate', 'igraph', 'plotly'), dependencies = T)"

# Workaround for Java to install correctly
RUN mkdir -p /usr/share/man/man1/

RUN R -e "install.packages(c('rgl', 'hdf5r', 'rJava'), dependencies = T)"
