#!/bin/bash
cat "python-versions.txt" | while read PYTHON_VERSION
do
    docker push ${DOCKER_REPO}:${PYTHON_VERSION}
    docker push ${DOCKER_REPO}:${PYTHON_VERSION}-bullseye
    docker push ${DOCKER_REPO}:${PYTHON_VERSION}-conda
done
